# Generated by Django 5.0.2 on 2024-03-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
