# Generated by Django 5.0.2 on 2024-03-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated',
        ),
    ]
