# Generated by Django 5.0.2 on 2024-03-12 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='purchases/')),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
