# Generated by Django 5.0.2 on 2024-03-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_alter_purchase_product'),
        ('Vendors', '0003_alter_vendors_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vendors.vendors'),
        ),
    ]
