# Generated by Django 5.0.2 on 2024-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('no_of_items', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('restocked', models.CharField(max_length=50)),
            ],
        ),
    ]
