# Generated by Django 5.0.2 on 2024-03-12 09:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('restocked', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('expiry', models.DateField(default=datetime.datetime.now, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
