# Generated by Django 5.0.2 on 2024-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addexpense',
            new_name='expense',
        ),
    ]
