# Generated by Django 5.0.2 on 2024-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
