# Generated by Django 5.0.2 on 2024-03-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addexpense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addexpense',
            old_name='describtion',
            new_name='description',
        ),
    ]
