# Generated by Django 5.0.2 on 2024-03-12 09:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('indate', models.DateField(default=datetime.datetime.now, null=True)),
                ('outdate', models.DateField(default=datetime.datetime.now, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
