# Generated by Django 5.0.2 on 2024-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='grandTotal',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='sales',
            name='gtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='vat',
            field=models.IntegerField(default=0),
        ),
    ]
