# Generated by Django 5.0.2 on 2024-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_grandtotal_sales_cost_sales_gtotal_sales_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
